# Site settings
title: Rookie-nerd's Tech Notes
url: "http://rookie-nerd.github.io"
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore]

# Theme customization - please change from the defaults!
style:
  # Color for top bar, links, etc
  highlight_color: '#3498db'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: fragno
    #stackexchange: 348619
    #stackoverflow: 348619
    twitter: fragno
    #facebook: zuck
    #tumblr: animalygifs
    #linkedin: philipjagielski
    #gplus: 110552447039675960964

  # "Hi, I'm _______"
  name: fragno
  email: fragno12@gmail.com
  tagline: "Every veteran comes from rookie"

  # Google Analytics key, leave blank to ignore
  google_analytics_key:
  google_analytics_domain:
  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: true
