# Site settings
title: Rookie-nerd's Tech Notes
email: fragno12@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Every veteran comes from rookie
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rookie-nerd.github.io" # the base hostname & protocol for your site
github_username:  fragno

# Build settings
markdown: kramdown
